name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        if: ${{ !env.ACT }}
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install dependecncies
        run: yarn install
      - name: Run lint
        run:
          yarn lint .
          #  test:
          #    name: Test
          #    runs-on: ubuntu-latest
          #    steps:
          #      - uses: actions/checkout@v3
          #      - name: Get yarn cache directory path
          #        id: yarn-cache-dir-path
          #        run: echo "YARN_CACHE_PATH=$(yarn cache dir)" >> $GITHUB_ENV
          #      - uses: actions/cache@v3
          #        with:
          #          path: ${{ env.YARN_CACHE_PATH }}
          #          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          #          restore-keys: |
          #            ${{ runner.os }}-yarn-
          #      - name: Install dependecncies
          #        run: yarn install
          #      - name: Run Test
          #        run: yarn test
